//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.mets.v2;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.loc.mets.v2 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.loc.mets.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MetsType }
     * 
     * @return
     *     the new instance of {@link MetsType }
     */
    public MetsType createMetsType() {
        return new MetsType();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     * @return
     *     the new instance of {@link FileType }
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link FileType.FContent }
     * 
     * @return
     *     the new instance of {@link FileType.FContent }
     */
    public FileType.FContent createFileTypeFContent() {
        return new FileType.FContent();
    }

    /**
     * Create an instance of {@link MdType }
     * 
     * @return
     *     the new instance of {@link MdType }
     */
    public MdType createMdType() {
        return new MdType();
    }

    /**
     * Create an instance of {@link MdType.MdWrap }
     * 
     * @return
     *     the new instance of {@link MdType.MdWrap }
     */
    public MdType.MdWrap createMdTypeMdWrap() {
        return new MdType.MdWrap();
    }

    /**
     * Create an instance of {@link DivType }
     * 
     * @return
     *     the new instance of {@link DivType }
     */
    public DivType createDivType() {
        return new DivType();
    }

    /**
     * Create an instance of {@link MetsType.FileSec }
     * 
     * @return
     *     the new instance of {@link MetsType.FileSec }
     */
    public MetsType.FileSec createMetsTypeFileSec() {
        return new MetsType.FileSec();
    }

    /**
     * Create an instance of {@link MdSecType }
     * 
     * @return
     *     the new instance of {@link MdSecType }
     */
    public MdSecType createMdSecType() {
        return new MdSecType();
    }

    /**
     * Create an instance of {@link MetsType.MetsHdr }
     * 
     * @return
     *     the new instance of {@link MetsType.MetsHdr }
     */
    public MetsType.MetsHdr createMetsTypeMetsHdr() {
        return new MetsType.MetsHdr();
    }

    /**
     * Create an instance of {@link MetsType.MetsHdr.Agent }
     * 
     * @return
     *     the new instance of {@link MetsType.MetsHdr.Agent }
     */
    public MetsType.MetsHdr.Agent createMetsTypeMetsHdrAgent() {
        return new MetsType.MetsHdr.Agent();
    }

    /**
     * Create an instance of {@link Mets }
     * 
     * @return
     *     the new instance of {@link Mets }
     */
    public Mets createMets() {
        return new Mets();
    }

    /**
     * Create an instance of {@link MetsType.StructSec }
     * 
     * @return
     *     the new instance of {@link MetsType.StructSec }
     */
    public MetsType.StructSec createMetsTypeStructSec() {
        return new MetsType.StructSec();
    }

    /**
     * Create an instance of {@link FileGrpType }
     * 
     * @return
     *     the new instance of {@link FileGrpType }
     */
    public FileGrpType createFileGrpType() {
        return new FileGrpType();
    }

    /**
     * Create an instance of {@link StructMapType }
     * 
     * @return
     *     the new instance of {@link StructMapType }
     */
    public StructMapType createStructMapType() {
        return new StructMapType();
    }

    /**
     * Create an instance of {@link ParType }
     * 
     * @return
     *     the new instance of {@link ParType }
     */
    public ParType createParType() {
        return new ParType();
    }

    /**
     * Create an instance of {@link SeqType }
     * 
     * @return
     *     the new instance of {@link SeqType }
     */
    public SeqType createSeqType() {
        return new SeqType();
    }

    /**
     * Create an instance of {@link AreaType }
     * 
     * @return
     *     the new instance of {@link AreaType }
     */
    public AreaType createAreaType() {
        return new AreaType();
    }

    /**
     * Create an instance of {@link FileType.FLocat }
     * 
     * @return
     *     the new instance of {@link FileType.FLocat }
     */
    public FileType.FLocat createFileTypeFLocat() {
        return new FileType.FLocat();
    }

    /**
     * Create an instance of {@link FileType.Stream }
     * 
     * @return
     *     the new instance of {@link FileType.Stream }
     */
    public FileType.Stream createFileTypeStream() {
        return new FileType.Stream();
    }

    /**
     * Create an instance of {@link FileType.TransformFile }
     * 
     * @return
     *     the new instance of {@link FileType.TransformFile }
     */
    public FileType.TransformFile createFileTypeTransformFile() {
        return new FileType.TransformFile();
    }

    /**
     * Create an instance of {@link FileType.FContent.XmlData }
     * 
     * @return
     *     the new instance of {@link FileType.FContent.XmlData }
     */
    public FileType.FContent.XmlData createFileTypeFContentXmlData() {
        return new FileType.FContent.XmlData();
    }

    /**
     * Create an instance of {@link MdType.MdRef }
     * 
     * @return
     *     the new instance of {@link MdType.MdRef }
     */
    public MdType.MdRef createMdTypeMdRef() {
        return new MdType.MdRef();
    }

    /**
     * Create an instance of {@link MdType.MdWrap.XmlData }
     * 
     * @return
     *     the new instance of {@link MdType.MdWrap.XmlData }
     */
    public MdType.MdWrap.XmlData createMdTypeMdWrapXmlData() {
        return new MdType.MdWrap.XmlData();
    }

    /**
     * Create an instance of {@link DivType.Mptr }
     * 
     * @return
     *     the new instance of {@link DivType.Mptr }
     */
    public DivType.Mptr createDivTypeMptr() {
        return new DivType.Mptr();
    }

    /**
     * Create an instance of {@link DivType.Fptr }
     * 
     * @return
     *     the new instance of {@link DivType.Fptr }
     */
    public DivType.Fptr createDivTypeFptr() {
        return new DivType.Fptr();
    }

    /**
     * Create an instance of {@link MetsType.FileSec.FileGrp }
     * 
     * @return
     *     the new instance of {@link MetsType.FileSec.FileGrp }
     */
    public MetsType.FileSec.FileGrp createMetsTypeFileSecFileGrp() {
        return new MetsType.FileSec.FileGrp();
    }

    /**
     * Create an instance of {@link MdSecType.MdGrp }
     * 
     * @return
     *     the new instance of {@link MdSecType.MdGrp }
     */
    public MdSecType.MdGrp createMdSecTypeMdGrp() {
        return new MdSecType.MdGrp();
    }

    /**
     * Create an instance of {@link MetsType.MetsHdr.AltRecordID }
     * 
     * @return
     *     the new instance of {@link MetsType.MetsHdr.AltRecordID }
     */
    public MetsType.MetsHdr.AltRecordID createMetsTypeMetsHdrAltRecordID() {
        return new MetsType.MetsHdr.AltRecordID();
    }

    /**
     * Create an instance of {@link MetsType.MetsHdr.MetsDocumentID }
     * 
     * @return
     *     the new instance of {@link MetsType.MetsHdr.MetsDocumentID }
     */
    public MetsType.MetsHdr.MetsDocumentID createMetsTypeMetsHdrMetsDocumentID() {
        return new MetsType.MetsHdr.MetsDocumentID();
    }

    /**
     * Create an instance of {@link MetsType.MetsHdr.Agent.Note }
     * 
     * @return
     *     the new instance of {@link MetsType.MetsHdr.Agent.Note }
     */
    public MetsType.MetsHdr.Agent.Note createMetsTypeMetsHdrAgentNote() {
        return new MetsType.MetsHdr.Agent.Note();
    }

}
