//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for agentComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="agentComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}agentIdentifier" maxOccurs="unbounded"/>
 *         <element ref="{http://www.loc.gov/premis/v3}agentName" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}agentType" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}agentVersion" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}agentNote" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}agentExtension" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}linkingEventIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}linkingRightsStatementIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}linkingEnvironmentIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="xmlID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       <attribute name="version" type="{http://www.loc.gov/premis/v3}version3" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "agentComplexType", propOrder = {
    "agentIdentifier",
    "agentName",
    "agentType",
    "agentVersion",
    "agentNote",
    "agentExtension",
    "linkingEventIdentifier",
    "linkingRightsStatementIdentifier",
    "linkingEnvironmentIdentifier"
})
public class AgentComplexType {

    @XmlElement(required = true)
    protected List<AgentIdentifierComplexType> agentIdentifier;
    protected List<StringPlusAuthority> agentName;
    protected StringPlusAuthority agentType;
    protected String agentVersion;
    protected List<String> agentNote;
    protected List<ExtensionComplexType> agentExtension;
    protected List<LinkingEventIdentifierComplexType> linkingEventIdentifier;
    protected List<LinkingRightsStatementIdentifierComplexType> linkingRightsStatementIdentifier;
    protected List<LinkingEnvironmentIdentifierComplexType> linkingEnvironmentIdentifier;
    @XmlAttribute(name = "xmlID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String xmlID;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the agentIdentifier property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentIdentifier property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAgentIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentIdentifierComplexType }
     * </p>
     * 
     * 
     * @return
     *     The value of the agentIdentifier property.
     */
    public List<AgentIdentifierComplexType> getAgentIdentifier() {
        if (agentIdentifier == null) {
            agentIdentifier = new ArrayList<>();
        }
        return this.agentIdentifier;
    }

    /**
     * Gets the value of the agentName property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentName property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAgentName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringPlusAuthority }
     * </p>
     * 
     * 
     * @return
     *     The value of the agentName property.
     */
    public List<StringPlusAuthority> getAgentName() {
        if (agentName == null) {
            agentName = new ArrayList<>();
        }
        return this.agentName;
    }

    /**
     * Gets the value of the agentType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getAgentType() {
        return agentType;
    }

    /**
     * Sets the value of the agentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setAgentType(StringPlusAuthority value) {
        this.agentType = value;
    }

    /**
     * Gets the value of the agentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgentVersion() {
        return agentVersion;
    }

    /**
     * Sets the value of the agentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgentVersion(String value) {
        this.agentVersion = value;
    }

    /**
     * Gets the value of the agentNote property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentNote property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAgentNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the agentNote property.
     */
    public List<String> getAgentNote() {
        if (agentNote == null) {
            agentNote = new ArrayList<>();
        }
        return this.agentNote;
    }

    /**
     * Gets the value of the agentExtension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentExtension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAgentExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionComplexType }
     * </p>
     * 
     * 
     * @return
     *     The value of the agentExtension property.
     */
    public List<ExtensionComplexType> getAgentExtension() {
        if (agentExtension == null) {
            agentExtension = new ArrayList<>();
        }
        return this.agentExtension;
    }

    /**
     * Gets the value of the linkingEventIdentifier property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkingEventIdentifier property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLinkingEventIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkingEventIdentifierComplexType }
     * </p>
     * 
     * 
     * @return
     *     The value of the linkingEventIdentifier property.
     */
    public List<LinkingEventIdentifierComplexType> getLinkingEventIdentifier() {
        if (linkingEventIdentifier == null) {
            linkingEventIdentifier = new ArrayList<>();
        }
        return this.linkingEventIdentifier;
    }

    /**
     * Gets the value of the linkingRightsStatementIdentifier property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkingRightsStatementIdentifier property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLinkingRightsStatementIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkingRightsStatementIdentifierComplexType }
     * </p>
     * 
     * 
     * @return
     *     The value of the linkingRightsStatementIdentifier property.
     */
    public List<LinkingRightsStatementIdentifierComplexType> getLinkingRightsStatementIdentifier() {
        if (linkingRightsStatementIdentifier == null) {
            linkingRightsStatementIdentifier = new ArrayList<>();
        }
        return this.linkingRightsStatementIdentifier;
    }

    /**
     * Gets the value of the linkingEnvironmentIdentifier property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkingEnvironmentIdentifier property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLinkingEnvironmentIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkingEnvironmentIdentifierComplexType }
     * </p>
     * 
     * 
     * @return
     *     The value of the linkingEnvironmentIdentifier property.
     */
    public List<LinkingEnvironmentIdentifierComplexType> getLinkingEnvironmentIdentifier() {
        if (linkingEnvironmentIdentifier == null) {
            linkingEnvironmentIdentifier = new ArrayList<>();
        }
        return this.linkingEnvironmentIdentifier;
    }

    /**
     * Gets the value of the xmlID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlID() {
        return xmlID;
    }

    /**
     * Sets the value of the xmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlID(String value) {
        this.xmlID = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
