//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for copyrightDocumentationIdentifierComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="copyrightDocumentationIdentifierComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}copyrightDocumentationIdentifierType"/>
 *         <element ref="{http://www.loc.gov/premis/v3}copyrightDocumentationIdentifierValue"/>
 *         <element ref="{http://www.loc.gov/premis/v3}copyrightDocumentationRole" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "copyrightDocumentationIdentifierComplexType", propOrder = {
    "copyrightDocumentationIdentifierType",
    "copyrightDocumentationIdentifierValue",
    "copyrightDocumentationRole"
})
public class CopyrightDocumentationIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority copyrightDocumentationIdentifierType;
    @XmlElement(required = true)
    protected String copyrightDocumentationIdentifierValue;
    protected StringPlusAuthority copyrightDocumentationRole;

    /**
     * Gets the value of the copyrightDocumentationIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getCopyrightDocumentationIdentifierType() {
        return copyrightDocumentationIdentifierType;
    }

    /**
     * Sets the value of the copyrightDocumentationIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setCopyrightDocumentationIdentifierType(StringPlusAuthority value) {
        this.copyrightDocumentationIdentifierType = value;
    }

    /**
     * Gets the value of the copyrightDocumentationIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrightDocumentationIdentifierValue() {
        return copyrightDocumentationIdentifierValue;
    }

    /**
     * Sets the value of the copyrightDocumentationIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrightDocumentationIdentifierValue(String value) {
        this.copyrightDocumentationIdentifierValue = value;
    }

    /**
     * Gets the value of the copyrightDocumentationRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getCopyrightDocumentationRole() {
        return copyrightDocumentationRole;
    }

    /**
     * Sets the value of the copyrightDocumentationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setCopyrightDocumentationRole(StringPlusAuthority value) {
        this.copyrightDocumentationRole = value;
    }

}
