//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for environmentRegistryComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="environmentRegistryComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentRegistryName"/>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentRegistryKey"/>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentRegistryRole" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "environmentRegistryComplexType", propOrder = {
    "environmentRegistryName",
    "environmentRegistryKey",
    "environmentRegistryRole"
})
public class EnvironmentRegistryComplexType {

    @XmlElement(required = true)
    protected String environmentRegistryName;
    @XmlElement(required = true)
    protected String environmentRegistryKey;
    protected StringPlusAuthority environmentRegistryRole;

    /**
     * Gets the value of the environmentRegistryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentRegistryName() {
        return environmentRegistryName;
    }

    /**
     * Sets the value of the environmentRegistryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentRegistryName(String value) {
        this.environmentRegistryName = value;
    }

    /**
     * Gets the value of the environmentRegistryKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentRegistryKey() {
        return environmentRegistryKey;
    }

    /**
     * Sets the value of the environmentRegistryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentRegistryKey(String value) {
        this.environmentRegistryKey = value;
    }

    /**
     * Gets the value of the environmentRegistryRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getEnvironmentRegistryRole() {
        return environmentRegistryRole;
    }

    /**
     * Sets the value of the environmentRegistryRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setEnvironmentRegistryRole(StringPlusAuthority value) {
        this.environmentRegistryRole = value;
    }

}
