//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for environmentDesignationComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="environmentDesignationComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentName"/>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentVersion" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentOrigin" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentDesignationNote" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentDesignationExtension" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "environmentDesignationComplexType", propOrder = {
    "environmentName",
    "environmentVersion",
    "environmentOrigin",
    "environmentDesignationNote",
    "environmentDesignationExtension"
})
public class EnvironmentDesignationComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority environmentName;
    protected String environmentVersion;
    protected String environmentOrigin;
    protected List<String> environmentDesignationNote;
    protected List<String> environmentDesignationExtension;

    /**
     * Gets the value of the environmentName property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getEnvironmentName() {
        return environmentName;
    }

    /**
     * Sets the value of the environmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setEnvironmentName(StringPlusAuthority value) {
        this.environmentName = value;
    }

    /**
     * Gets the value of the environmentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentVersion() {
        return environmentVersion;
    }

    /**
     * Sets the value of the environmentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentVersion(String value) {
        this.environmentVersion = value;
    }

    /**
     * Gets the value of the environmentOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentOrigin() {
        return environmentOrigin;
    }

    /**
     * Sets the value of the environmentOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentOrigin(String value) {
        this.environmentOrigin = value;
    }

    /**
     * Gets the value of the environmentDesignationNote property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the environmentDesignationNote property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getEnvironmentDesignationNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the environmentDesignationNote property.
     */
    public List<String> getEnvironmentDesignationNote() {
        if (environmentDesignationNote == null) {
            environmentDesignationNote = new ArrayList<>();
        }
        return this.environmentDesignationNote;
    }

    /**
     * Gets the value of the environmentDesignationExtension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the environmentDesignationExtension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getEnvironmentDesignationExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the environmentDesignationExtension property.
     */
    public List<String> getEnvironmentDesignationExtension() {
        if (environmentDesignationExtension == null) {
            environmentDesignationExtension = new ArrayList<>();
        }
        return this.environmentDesignationExtension;
    }

}
