//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for environmentFunctionComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="environmentFunctionComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentFunctionType"/>
 *         <element ref="{http://www.loc.gov/premis/v3}environmentFunctionLevel"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "environmentFunctionComplexType", propOrder = {
    "environmentFunctionType",
    "environmentFunctionLevel"
})
public class EnvironmentFunctionComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority environmentFunctionType;
    @XmlElement(required = true)
    protected String environmentFunctionLevel;

    /**
     * Gets the value of the environmentFunctionType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getEnvironmentFunctionType() {
        return environmentFunctionType;
    }

    /**
     * Sets the value of the environmentFunctionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setEnvironmentFunctionType(StringPlusAuthority value) {
        this.environmentFunctionType = value;
    }

    /**
     * Gets the value of the environmentFunctionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentFunctionLevel() {
        return environmentFunctionLevel;
    }

    /**
     * Sets the value of the environmentFunctionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentFunctionLevel(String value) {
        this.environmentFunctionLevel = value;
    }

}
