//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fixityComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="fixityComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}messageDigestAlgorithm"/>
 *         <element ref="{http://www.loc.gov/premis/v3}messageDigest"/>
 *         <element ref="{http://www.loc.gov/premis/v3}messageDigestOriginator" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fixityComplexType", propOrder = {
    "messageDigestAlgorithm",
    "messageDigest",
    "messageDigestOriginator"
})
public class FixityComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority messageDigestAlgorithm;
    @XmlElement(required = true)
    protected String messageDigest;
    protected StringPlusAuthority messageDigestOriginator;

    /**
     * Gets the value of the messageDigestAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getMessageDigestAlgorithm() {
        return messageDigestAlgorithm;
    }

    /**
     * Sets the value of the messageDigestAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setMessageDigestAlgorithm(StringPlusAuthority value) {
        this.messageDigestAlgorithm = value;
    }

    /**
     * Gets the value of the messageDigest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageDigest() {
        return messageDigest;
    }

    /**
     * Sets the value of the messageDigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageDigest(String value) {
        this.messageDigest = value;
    }

    /**
     * Gets the value of the messageDigestOriginator property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getMessageDigestOriginator() {
        return messageDigestOriginator;
    }

    /**
     * Sets the value of the messageDigestOriginator property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setMessageDigestOriginator(StringPlusAuthority value) {
        this.messageDigestOriginator = value;
    }

}
