//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inhibitorsComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="inhibitorsComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}inhibitorType"/>
 *         <element ref="{http://www.loc.gov/premis/v3}inhibitorTarget" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}inhibitorKey" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inhibitorsComplexType", propOrder = {
    "inhibitorType",
    "inhibitorTarget",
    "inhibitorKey"
})
public class InhibitorsComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority inhibitorType;
    protected List<StringPlusAuthority> inhibitorTarget;
    protected String inhibitorKey;

    /**
     * Gets the value of the inhibitorType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getInhibitorType() {
        return inhibitorType;
    }

    /**
     * Sets the value of the inhibitorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setInhibitorType(StringPlusAuthority value) {
        this.inhibitorType = value;
    }

    /**
     * Gets the value of the inhibitorTarget property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inhibitorTarget property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getInhibitorTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringPlusAuthority }
     * </p>
     * 
     * 
     * @return
     *     The value of the inhibitorTarget property.
     */
    public List<StringPlusAuthority> getInhibitorTarget() {
        if (inhibitorTarget == null) {
            inhibitorTarget = new ArrayList<>();
        }
        return this.inhibitorTarget;
    }

    /**
     * Gets the value of the inhibitorKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInhibitorKey() {
        return inhibitorKey;
    }

    /**
     * Sets the value of the inhibitorKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInhibitorKey(String value) {
        this.inhibitorKey = value;
    }

}
