//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for otherRightsInformationComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="otherRightsInformationComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}otherRightsDocumentationIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}otherRightsBasis"/>
 *         <element ref="{http://www.loc.gov/premis/v3}otherRightsApplicableDates" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}otherRightsNote" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "otherRightsInformationComplexType", propOrder = {
    "otherRightsDocumentationIdentifier",
    "otherRightsBasis",
    "otherRightsApplicableDates",
    "otherRightsNote"
})
public class OtherRightsInformationComplexType {

    protected List<OtherRightsDocumentationIdentifierComplexType> otherRightsDocumentationIdentifier;
    @XmlElement(required = true)
    protected StringPlusAuthority otherRightsBasis;
    protected StartAndEndDateComplexType otherRightsApplicableDates;
    protected List<String> otherRightsNote;

    /**
     * Gets the value of the otherRightsDocumentationIdentifier property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherRightsDocumentationIdentifier property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getOtherRightsDocumentationIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherRightsDocumentationIdentifierComplexType }
     * </p>
     * 
     * 
     * @return
     *     The value of the otherRightsDocumentationIdentifier property.
     */
    public List<OtherRightsDocumentationIdentifierComplexType> getOtherRightsDocumentationIdentifier() {
        if (otherRightsDocumentationIdentifier == null) {
            otherRightsDocumentationIdentifier = new ArrayList<>();
        }
        return this.otherRightsDocumentationIdentifier;
    }

    /**
     * Gets the value of the otherRightsBasis property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getOtherRightsBasis() {
        return otherRightsBasis;
    }

    /**
     * Sets the value of the otherRightsBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setOtherRightsBasis(StringPlusAuthority value) {
        this.otherRightsBasis = value;
    }

    /**
     * Gets the value of the otherRightsApplicableDates property.
     * 
     * @return
     *     possible object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public StartAndEndDateComplexType getOtherRightsApplicableDates() {
        return otherRightsApplicableDates;
    }

    /**
     * Sets the value of the otherRightsApplicableDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public void setOtherRightsApplicableDates(StartAndEndDateComplexType value) {
        this.otherRightsApplicableDates = value;
    }

    /**
     * Gets the value of the otherRightsNote property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherRightsNote property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getOtherRightsNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the otherRightsNote property.
     */
    public List<String> getOtherRightsNote() {
        if (otherRightsNote == null) {
            otherRightsNote = new ArrayList<>();
        }
        return this.otherRightsNote;
    }

}
