//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(
        namespace = "http://www.loc.gov/premis/v3",
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @jakarta.xml.bind.annotation.XmlNs(
                        prefix = "premis",
                        namespaceURI = "http://www.loc.gov/premis/v3"
                )
        }
)
package gov.loc.premis.v3;
