//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for preservationLevelComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="preservationLevelComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}preservationLevelType" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}preservationLevelValue"/>
 *         <element ref="{http://www.loc.gov/premis/v3}preservationLevelRole" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}preservationLevelRationale" maxOccurs="unbounded" minOccurs="0"/>
 *         <element ref="{http://www.loc.gov/premis/v3}preservationLevelDateAssigned" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "preservationLevelComplexType", propOrder = {
    "preservationLevelType",
    "preservationLevelValue",
    "preservationLevelRole",
    "preservationLevelRationale",
    "preservationLevelDateAssigned"
})
public class PreservationLevelComplexType {

    protected StringPlusAuthority preservationLevelType;
    @XmlElement(required = true)
    protected StringPlusAuthority preservationLevelValue;
    protected StringPlusAuthority preservationLevelRole;
    protected List<String> preservationLevelRationale;
    protected String preservationLevelDateAssigned;

    /**
     * Gets the value of the preservationLevelType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getPreservationLevelType() {
        return preservationLevelType;
    }

    /**
     * Sets the value of the preservationLevelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setPreservationLevelType(StringPlusAuthority value) {
        this.preservationLevelType = value;
    }

    /**
     * Gets the value of the preservationLevelValue property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getPreservationLevelValue() {
        return preservationLevelValue;
    }

    /**
     * Sets the value of the preservationLevelValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setPreservationLevelValue(StringPlusAuthority value) {
        this.preservationLevelValue = value;
    }

    /**
     * Gets the value of the preservationLevelRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getPreservationLevelRole() {
        return preservationLevelRole;
    }

    /**
     * Sets the value of the preservationLevelRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setPreservationLevelRole(StringPlusAuthority value) {
        this.preservationLevelRole = value;
    }

    /**
     * Gets the value of the preservationLevelRationale property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preservationLevelRationale property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPreservationLevelRationale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the preservationLevelRationale property.
     */
    public List<String> getPreservationLevelRationale() {
        if (preservationLevelRationale == null) {
            preservationLevelRationale = new ArrayList<>();
        }
        return this.preservationLevelRationale;
    }

    /**
     * Gets the value of the preservationLevelDateAssigned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreservationLevelDateAssigned() {
        return preservationLevelDateAssigned;
    }

    /**
     * Sets the value of the preservationLevelDateAssigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreservationLevelDateAssigned(String value) {
        this.preservationLevelDateAssigned = value;
    }

}
