//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relatedEventIdentifierComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="relatedEventIdentifierComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}relatedEventIdentifierType"/>
 *         <element ref="{http://www.loc.gov/premis/v3}relatedEventIdentifierValue"/>
 *         <element ref="{http://www.loc.gov/premis/v3}relatedEventSequence" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="RelEventXmlID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       <attribute name="simpleLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedEventIdentifierComplexType", propOrder = {
    "relatedEventIdentifierType",
    "relatedEventIdentifierValue",
    "relatedEventSequence"
})
public class RelatedEventIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority relatedEventIdentifierType;
    @XmlElement(required = true)
    protected String relatedEventIdentifierValue;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger relatedEventSequence;
    @XmlAttribute(name = "RelEventXmlID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object relEventXmlID;
    @XmlAttribute(name = "simpleLink")
    @XmlSchemaType(name = "anyURI")
    protected String simpleLink;

    /**
     * Gets the value of the relatedEventIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRelatedEventIdentifierType() {
        return relatedEventIdentifierType;
    }

    /**
     * Sets the value of the relatedEventIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRelatedEventIdentifierType(StringPlusAuthority value) {
        this.relatedEventIdentifierType = value;
    }

    /**
     * Gets the value of the relatedEventIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedEventIdentifierValue() {
        return relatedEventIdentifierValue;
    }

    /**
     * Sets the value of the relatedEventIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedEventIdentifierValue(String value) {
        this.relatedEventIdentifierValue = value;
    }

    /**
     * Gets the value of the relatedEventSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelatedEventSequence() {
        return relatedEventSequence;
    }

    /**
     * Sets the value of the relatedEventSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelatedEventSequence(BigInteger value) {
        this.relatedEventSequence = value;
    }

    /**
     * Gets the value of the relEventXmlID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRelEventXmlID() {
        return relEventXmlID;
    }

    /**
     * Sets the value of the relEventXmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRelEventXmlID(Object value) {
        this.relEventXmlID = value;
    }

    /**
     * Gets the value of the simpleLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLink() {
        return simpleLink;
    }

    /**
     * Sets the value of the simpleLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLink(String value) {
        this.simpleLink = value;
    }

}
