//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package gov.loc.premis.v3;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relatedObjectIdentifierComplexType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="relatedObjectIdentifierComplexType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.loc.gov/premis/v3}relatedObjectIdentifierType"/>
 *         <element ref="{http://www.loc.gov/premis/v3}relatedObjectIdentifierValue"/>
 *         <element ref="{http://www.loc.gov/premis/v3}relatedObjectSequence" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="RelObjectXmlID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       <attribute name="simpleLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedObjectIdentifierComplexType", propOrder = {
    "relatedObjectIdentifierType",
    "relatedObjectIdentifierValue",
    "relatedObjectSequence"
})
public class RelatedObjectIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority relatedObjectIdentifierType;
    @XmlElement(required = true)
    protected String relatedObjectIdentifierValue;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger relatedObjectSequence;
    @XmlAttribute(name = "RelObjectXmlID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object relObjectXmlID;
    @XmlAttribute(name = "simpleLink")
    @XmlSchemaType(name = "anyURI")
    protected String simpleLink;

    /**
     * Gets the value of the relatedObjectIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRelatedObjectIdentifierType() {
        return relatedObjectIdentifierType;
    }

    /**
     * Sets the value of the relatedObjectIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRelatedObjectIdentifierType(StringPlusAuthority value) {
        this.relatedObjectIdentifierType = value;
    }

    /**
     * Gets the value of the relatedObjectIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedObjectIdentifierValue() {
        return relatedObjectIdentifierValue;
    }

    /**
     * Sets the value of the relatedObjectIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedObjectIdentifierValue(String value) {
        this.relatedObjectIdentifierValue = value;
    }

    /**
     * Gets the value of the relatedObjectSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelatedObjectSequence() {
        return relatedObjectSequence;
    }

    /**
     * Sets the value of the relatedObjectSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelatedObjectSequence(BigInteger value) {
        this.relatedObjectSequence = value;
    }

    /**
     * Gets the value of the relObjectXmlID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRelObjectXmlID() {
        return relObjectXmlID;
    }

    /**
     * Sets the value of the relObjectXmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRelObjectXmlID(Object value) {
        this.relObjectXmlID = value;
    }

    /**
     * Gets the value of the simpleLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLink() {
        return simpleLink;
    }

    /**
     * Sets the value of the simpleLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLink(String value) {
        this.simpleLink = value;
    }

}
